name: Graphene
version: '${version}'
main: org.craftamethyst.graphene.Graphene
api-version: 1.13
depend: []
softdepend: 
  - PlaceholderAPI
authors: [ QianMo_ProMax,ZCRAFT ]
commands:
  graphene:
    description: 'The main command of Graphene'
    aliases: [ grap ]
